services:
  - type: web
    name: techwizards-frontend
    env: node
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist 